browser-use/web-ui

webui.py
Add logs in case user selected on browser but either forgot to add the right env vars (CHROME_PATH, CHROME_USER_DATA) or set them to incorrect paths
=> fix: log for own browser env var issues

webui.py
To suppress the below `UserWarning`, we can set a default value for `LLM Provider` and `LLM Model Name`. The `warning` was as below:
```
H:\Documents\Work\browser-web-ui\myenv\Lib\site-packages\gradio\components\dropdown.py:226: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
```
=> feat: add llm provider and model default value to supperss `UserWarning`

webui.py
Because it will cause errors when not setting in base_url and api_key
=> remove default api key

src/agent/custom_agent.py, src/utils/agent_state.py, webui.py
Let's try to merge this PR.  I created it from my primary and merged it with my branch.
=> Button Fix PR v3

Dockerfile, docker-compose.yml
**Issue:** 
on non amd64 architectures google chrome will not install.
**Details:**
From running dockerfile:
```
RUN apt-get install -y google-chrome-stable
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package google-chrome-stable
```
**Solution:**
Set docker architecture explicitly ensures google-chrome is available to install.
Note: also added netcat as it was missing to let the health check pass.
=> fix: set architecture explicitly in docker-compose

src/agent/custom_agent.py
Found some repeated code in the get_next_action method. Basically merged the duplicate logic for processing responses and handling messages into a single flow. The deepseek logging is still there and everything works exactly the same - just cleaner and easier to maintain now.
=> refactor: remove code duplication in get_next_action method

tests/test_llm_api.py
Cleaned up the LLM testing code to be less repetitive by merging all the common logic into shared functions and a config class. Everything should work the same as before (I was only able to test it with Gemini, as it's _free_, but the rest should work as well).
=> refactor: simplify LLM tests and remove duplication

src/utils/utils.py, webui.py
This PR adds proper error handling in the UI for missing API keys, addressing issue #188. Previously, missing API keys resulted in tracebacks in the console, but no clear error was shown in the UI. This made it difficult to understand what went wrong. Now, API key checks are performed at the start of the `get_llm_model` function in `src/utils/utils.py`. I've also added a `PROVIDER_DISPLAY_NAMES` constant for more user-friendly error messages and a `handle_api_key_error` function that leverages `gr.Error` to display clear error messages directly in the UI. If an API key is missing, you'll now see an error message right away. The `run_browser_agent` and `run_with_stream` functions in `webui.py` have been adjusted to ensure these `gr.Error` exceptions are handled properly.
=> fix: display missing API key errors in UI

src/agent/custom_prompts.py, src/utils/utils.py, webui.py
This PR introduces support for OpenAI's O3-mini model and fixes theme handling in the web UI.
1. **O3-mini Model Support**
- Added O3-mini to the OpenAI model options
- Updated model selection dropdown to include the new option
1. **Theme Handling**
- Removed forced dark theme JavaScript code
- UI now respects system/browser theme preferences
- Theme can be controlled via `--theme` argument or browser settings
2. **Code Improvements**
- Fixed JSON template escape sequence in custom prompts
- Improved code readability and maintainability
- Verified O3-mini model appears in dropdown
- Confirmed theme switching works correctly
- Tested JSON template parsing
- Users need appropriate OpenAI API access to use the O3-mini model
- Theme changes are now consistent with Gradio's theme system
=> feat: add OpenAI O3-mini model support and fix theme handling

.env.example
Added the missing endpoints for Anthropic (`ANTHROPIC_ENDPOINT`) and Mistral (`MISTRAL_ENDPOINT`) in the example env file. Also added Mistral's API key env var (`MISTRAL_API_KEY`).
=> feat: add missing endpoints and keys for Mistral and Anthropic

src/utils/utils.py
The ollama provider appears to incorrectly ignore the OLLAMA_ENDPOINT env var, unlike other provider implementations. In the same `elif` clause, the `base_url` has already been conditionally read, it's just not used.
=> fix: ollama provider not respecting OLLAMA_ENDPOINT env var

src/utils/deep_research.py, webui.py
1. fix some bugs.
2. add stop button.
3. add use own browser.
=> add stop button and use own browser

README.md, src/utils/utils.py, tests/test_browser_use.py, tests/test_llm_api.py
Renamed `gemini` to `google` across the codebase to make it consistent with `GOOGLE_API_KEY` and with the rest of the providers (e.g., `openai`, `anthropic`, `deepseek`, etc.), which are all company names instead of model names.
=> Rename `gemini` to `google` for consistency

src/utils/utils.py
Hello,
Thank you for creating such an amazing project!
Google Gemini 2.0 Flash is now GA and they have added 2.0 pro recently. This pr aims to correct the experimental Gemini 2.0 Flash name from `gemini-2.0-flash-exp` to `gemini-2.0-flash` and add support to 2.0 pro model.
ref: [Gemini 2.0](https://cloud.google.com/vertex-ai/generative-ai/docs/gemini-v2#2.0-pro)
ref: [Gemini models](https://ai.google.dev/gemini-api/docs/models/gemini#gemini-2.0-flash)
=> feat: update and add new google models

src/utils/utils.py, webui.py
Replaced the `handle_api_key_error` function with a `MissingAPIKeyError` exception class, removing the need for `gr.Error` (which has now been moved to `webui.py`), and made the error more cleaner/concise.
Also, to avoid unnecessarily importing `gradio` during API tests with `test_llm_api` (since it does not use the Gradio UI), the import has been moved inside `update_model_dropdown`, reducing loading time.
=> Better API key error handling

src/utils/utils.py
According to Mistral's documantation: https://docs.mistral.ai/getting-started/models/models_overview/ there is no such model as `mixtral-large-latest` there is, however, `pixtral-large-latest`. This looks like a typo introduced a few days ago.
=> Correct Mistral's multimodal model name

src/utils/mcp_client.py
Removed duplicates and unused imports in `/src/utils/mcp_client.py`
---
Removed duplicate and unused imports from `mcp_client.py` to clean up the code and reduce clutter.
=> chore: remove duplicate imports

src/webui/components/browser_use_agent_tab.py, src/webui/webui_manager.py
This PR addresses two Gradio deprecation warnings. It fixes the following issues:
1.  `...\web-ui\.venv\Lib\site-packages\gradio\blocks.py:1925: DeprecationWarning: The 'bubble_full_width' parameter is deprecated and will be removed in a future version. This parameter no longer has any effect.`
2.  `...\web-ui\src\webui\webui_manager.py:107: UserWarning: You have not specified a value for the 'type' parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead...`
---
Removed deprecated Gradio parameters and set the correct type for chatbot messages to resolve deprecation warnings.
- **Bug Fixes**
- Removed the unused bubble_full_width parameter.
- Set type="messages" for …
=> fix: address gradio deprecation warnings

Dockerfile
Update the Dockerfile to use Patchright instead of Playwright, addressing issue #574 
* Set `ENV PLAYWRIGHT_BROWSERS_PATH=/ms-patchright` to define the browser installation path for Patchright
* Replaced Playwright installation commands with Patchright equivalents:
```dockerfile
RUN patchright install --with-deps chromium
RUN patchright install-deps
```
- Verified that the container builds successfully with the new configuration
Closes #574 
Sorry, I deleted the repo accidentally. This PR is same to #579
=> Update patchright in Dockerfile

Dockerfile, README.md, docker-compose.yml, requirements.txt, src/agent/browser_use/browser_use_agent.py, src/agent/deep_research/deep_research_agent.py, src/browser/custom_browser.py, src/browser/custom_context.py, src/webui/components/browser_use_agent_tab.py, tests/test_agents.py, tests/test_playwright.py
1. upgrade bu==0.1.47
2. change patchright to playwright
---
Upgraded browser-use to version 0.1.47 and replaced all uses of patchright with playwright for browser automation.
- **Dependencies**
- Updated requirements and Docker setup to use playwright instead of patchright.
- **Refactors**
- Changed all imports and commands from patchright to playwright.
- Updated browser launch logic and tests to use new context configuration for window size.
=> upgrade to bu==0.1.47

src/webui/webui_manager.py
- In the WebuiManager.load_config method, retrieve the value of `planner_llm_provider` before setting the model name.
- When setting the value for `planner_llm_model_name`, dynamically update its choices based on the provider, and use `gr.Dropdown(value=..., choices=..., allow_custom_value=True)` to update the component.
- All other components remain unchanged.
- When using the "Load Config" feature, the planner_llm_model_name dropdown will now correctly display the model name according to the loaded configuration, without requiring manual reselection.
- This approach can be extended to other dropdowns with similar dependencies if needed.
1. In the UI, select different values for planner_llm_provider and planner_llm_model_name, then save the configuration.
2. Restart the WebUI or switch …
=> Fix `planner_llm_model_name` Not Loaded Correctly When Using "Load Config"

src/agent/deep_research/deep_research_agent.py, src/webui/components/deep_research_agent_tab.py
https://github.com/browser-use/web-ui/blob/886ba8f5354dca96a544ed7b7072fb41e4dcf850/src/agent/deep_research/deep_research_agent.py#L1115-L1115
https://github.com/browser-use/web-ui/blob/886ba8f5354dca96a544ed7b7072fb41e4dcf850/src/agent/deep_research/deep_research_agent.py#L1115-L1115
Fix the issue need to validate the `save_dir` parameter before using it to construct file paths. The best approach is to ensure that the constructed path is contained within a safe root directory. This can be achieved by normalizing the path using `os.path.normpath` and verifying that it starts with the intended root directory.
Steps to implement the fix:
1. Introduce a `safe_root_dir` variable to define the root directory where files can be saved.
2. Normalize the `save_dir` parameter using …
=> Fix uncontrolled data used in path expression
