- src/agent/custom_prompts.py
> chore: update custom_prompts.py

- requirements.txt
- src/agent/custom_agent.py
- src/agent/custom_massage_manager.py
- src/agent/custom_prompts.py
- src/browser/custom_context.py
- src/utils/utils.py
- tests/test_browser_use.py
- webui.py
1. Webui add max_actions_per_step and tool_call_in_content options.
2. Fix ollama parse error.
3. Update requirements.txt, gemini is officially supported, use `pip install -r requirements.txt` .
4. Fix Agent and BrowserContext to adapt new version of browser-use.
> feat: adpat to new version of browser-use

- webui.py
Browser Settings TAB
--> Added check box for enable or disable recordings
enable --> can edit the recordings path and videos are saved
disable --> cannot edit the recordings path and videos are not saved
> Enable/Disable Recordings

- src/agent/custom_massage_manager.py
- webui.py
1. fix tool_calls example
2. add trace path defined on webui
> add trace path and fix tool_calls example

- .env.example
- Dockerfile
- README.md
- docker-compose.yml
- src/browser/config.py
- src/browser/custom_browser.py
- src/browser/custom_context.py
- supervisord.conf
- webui.py
- Added `BrowserPersistenceConfig` class to manage browser persistence settings
- Implemented persistence checks in browser and context closing operations
- Added environment variable support for `CHROME_PERSISTENT_SESSION`
- Modified context manager to respect persistence settings
- Maintained backward compatibility with non-persistent mode
- Created persistence configuration to local codebase (`src/browser/config.py`)
- Updated imports to use local implementation
- Added proper type hints and documentation
- Maintained existing code style and formatting
- Added Docker support with browser persistence when required
- Implemented VNC for browser visualization
- Added environment variable configuration through Docker Compose
1. **Persistent Browser Sessions**
- Browser stays open between …
> Feat  add docker support and environment configuration updated

- README.md
Update readme:
1. Keep browser open
2. Docker setup
3. Re-format
> add  keep browser open and docker setup to readme

- webui.py
> feat: initialize browser and close it to resolve `UnboundLocalError`.

- Dockerfile
update fonts packages for installation
> feat: add font packages to install in Dockerfile

- .env.example
- src/utils/utils.py
- Added `OLLAMA_ENDPOINT` environment variable to `.env.example`
- Updated `get_llm_model` function in `src/utils/utils.py` to use the new `OLLAMA_ENDPOINT` environment variable if not provided
> feat: add Ollama endpoint configuration

- README.md
minor grammar correct, removing incorrect use of word 'a'.
> Update README.md minor grammar update

- README.md
Made the `README.md` installation guide way easier to follow. And added proper OS-specific instructions (Windows/Mac/Linux). Overall, it should be more clearer now.
> Improve `README.md` installation guide clarity and structure

- README.md
Added alternative for venv activation in Windows.
It's only a single comannd - the rest of the flow remains the same.
> Added alternative activation command for Windows

- src/agent/custom_agent.py
- src/agent/custom_message_manager.py
> fix: correct typo

- README.md
Remove not related text from README.md
> Remove not related text from README.md

- .env.example
- src/utils/utils.py
- tests/test_llm_api.py
Adding a new model provider which supports vision and an experts long text. 
also corrected image extension as the doubao ark model requires the image url to match with the image extension(encoding)
> Adding Moonshot model and correct image extension 

- src/agent/custom_agent.py
- webui.py
Hi,
I added support to use SENSITIVE_xxx variables such its possible to do.
```
Go to https://time.delegate.dk/ListTimeEntries and sign in with $SENSITIVE_x_email and $SENSITIVE_x_password.
Search for the project 371020 remember to click it in the dropdown when searching.
Select sprint .../
Find a worktiem for Segmentation PL and if not able to, just type it in the comment field.
Add 4 hours for monday.
When you get to the two factor step, just wait until i approve it on my phone - just sleep and check back in every 5sec if they UI have moved on to the next screen.
Its the 19/feb today.
```
and it uses variables in environment variables to avoid passwords and such being visible in screens.
> feat: added supportfor sensitive variables

- .env.example
- src/utils/deep_research.py
- webui.py
This PR allows the usage of CDP so we can use REMOTE chrome instances.
> feat: allow chrome cdp in env

- src/utils/utils.py
Renamed `model_name` to `model` and `google_api_key` to `api_key` for consistency with the others.
> chore: update parameter names for consistency

- .env.example
- docker-compose.yml
- requirements.txt
- src/utils/utils.py
- tests/test_llm_api.py
This PR adds IBM watsonx model support to browser-use web-ui
It covers the below changes
- Updated `.env.example` and `docker-compose.yml` files to include IBM watsonx environment variables 
- Added `langchain-ibm==0.3.10` as a dependency
- Added `ibm` as a model provider along with the `ChatWatsonx` support
- Added a test case to verify the changes
- Attached a screenshot of the test case execution
---
Added support for IBM watsonx models, allowing users to select IBM as a provider in the web UI.
- **Dependencies**
- Added langchain-ibm to requirements.
- **Configuration**
- Updated .env.example and docker-compose.yml with IBM environment variables.
- **Features**
- Enabled IBM model selection and usage.
- Added tests for IBM model integration.
> Added IBM watsonx model support

- requirements.txt
- src/agent/deep_research/deep_research_agent.py
- src/browser/custom_context.py
- src/webui/components/browser_use_agent_tab.py
Update browser-use version requirements.txt
---
Updated the browser-use package in requirements.txt from version 0.1.42 to 0.1.43.
> Update browser-use version  requirements.txt 0.1.45 

- requirements.txt
0.1.48 Update requirements.txt
---
Updated browser-use dependency to version 0.1.48 in requirements.txt.
> 0.1.48 Update requirements.txt
